spring:
  zipkin:
    base-url: ${ZIPKIN_URL:http://zipkin:9411}/

management:
  endpoints:
    web:
      exposure:
        include: "*"

  metrics:
    distribution:
      percentiles-histogram:
        http:
          server:
            requests: false
      percentiles:
        http:
          server:
            requests: 0.5, 0.9, 0.95, 0.99, 0.999
    tags:
      application: ${spring.application.name}

eureka:
  instance:
    hostname: discovery
  client:
    registerWithEureka: false
    fetchRegistry: false

ribbon:
  eureka:
    enabled: true