apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8n-service-products
  labels:
    app: k8n-service-products
spec:
  replicas: 3
  selector:
    matchLabels:
      app: k8n-service-products
  template:
    metadata:
      labels:
        app: k8n-service-products
    spec:
      containers:
        - name: containerized-products
          image: tanerdiler/service-products-api:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 2222